/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a new user
         * @description This endpoint allows creating a new user in the system
         */
        post: operations["createUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Error: {
            /** @description A detailed explanation of the error */
            detail: string;
            /** @description The HTTP status code for the error */
            status: number;
            /** @description A short description of the error */
            title: string;
        };
        CreateUser: {
            data: {
                /** @example userCreate */
                type: string;
                attributes: {
                    /** @description The user's name */
                    name: string;
                    /** @description The user's password */
                    password: string;
                    /** @description The user's username */
                    username: string;
                };
            };
        };
        UpdateUser: {
            data: {
                /** @example userUpdate */
                type: string;
                attributes: {
                    /** @description The user's avatar */
                    avatar?: string;
                    /** @description The user's name */
                    name?: string;
                    /** @description The user's password */
                    password: string;
                    /** @description The user's username */
                    username?: string;
                };
            };
        };
        User: {
            data: {
                /** @example user */
                type: string;
                /** @description Unique ID of the user */
                id?: number;
                attributes: {
                    /** @description The user's avatar */
                    avatar: string;
                    /** @description The user's name */
                    name: string;
                    /** @description The user's password */
                    password: string;
                    /** @description The user's username */
                    username: string;
                };
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description User data */
        requestBody?: {
            content: {
                "application/vnd.api+json": components["schemas"]["CreateUser"];
            };
        };
        responses: {
            /** @description User created successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": components["schemas"]["User"];
                };
            };
            /** @description Bad request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": components["schemas"]["Error"];
                };
            };
            /** @description Server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/vnd.api+json": components["schemas"]["Error"];
                };
            };
        };
    };
}
