name: Deploy API Infrastructure

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-api-infrastructure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configure credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{secrets.AWS_ROLE}}
          role-session-name: FederatedOIDC
          aws-region: us-east-1
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.2.0
      - name: Init (Development)
        run: terraform init
        working-directory: ./ask-me-anything-api/src/shared/infrastructure/cloud/development
      - name: Plan (Development)
        run: terraform plan
        working-directory: ./ask-me-anything-api/src/shared/infrastructure/cloud/development
      - name: Apply (Development)
        run: terraform apply -auto-approve
        working-directory: ./ask-me-anything-api/src/shared/infrastructure/cloud/development
