name: Build and Deploy

on:
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy-development:
    runs-on: ubuntu-latest
    steps:
      - name: Clone (Development)
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          role-to-assume: arn:aws:iam::045619769161:role/GitHubActionsRole
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: us-east-1
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.2.0
      - name: Init (Development)
        run: terraform init
        working-directory: ./ask-me-anything-api/src/infrastructure/cloud/development
        if: ${{ github.event_name == 'workflow_dispatch' }}
      - name: Apply (Development)
        run: terraform apply -auto-approve
        working-directory: ./ask-me-anything-api/src/infrastructure/cloud/development
        if: ${{ github.event_name == 'workflow_dispatch' }}
